services:
  local-postgresql:
    container_name: local-postgresql
    build:
      context: .
      dockerfile: local-postgresql.Dockerfile
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: acKLQLqf5dYaPpnBkT
      POSTGRES_DB: test-db
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgresql.conf:/var/lib/postgresql/data/postgresql.conf
    networks:
      my_network:
        ipv4_address: 172.18.0.2
    ports:
      - "5433:5432"

  local-mysql:
    image: mysql:latest
    container_name: local-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test-db
      MYSQL_USER: local-user
      MYSQL_PASSWORD: AHRmA7nD9PBa6zkm3Q
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      my_network:
        ipv4_address: 172.18.0.3
    ports:
      - "3307:3306"

  local-mssql:
    image: mcr.microsoft.com/mssql/server:latest
    container_name: local-mssql
    environment:
      SA_PASSWORD: "d8KEtHahXskAy5a6k6"
      ACCEPT_EULA: "Y"
    volumes:
      - mssql_data:/var/opt/mssql
    networks:
      my_network:
        ipv4_address: 172.18.0.4
    ports:
      - "1434:1433"

  local-mongodb:
    image: mongo:latest
    container_name: local-mongodb
    volumes:
      - mongo_data:/data/db
    networks:
      my_network:
        ipv4_address: 172.18.0.5
    ports:
      - "27017:27017"

  local-seq:
    image: datalust/seq:latest
    container_name: local-seq
    environment:
      ACCEPT_EULA: "Y"
      SEQ_API_CANONICALURI: "https://seq.example.com"
      SEQ_FIRSTRUN_ADMINPASSWORDHASH: "QF7lUK4BfMJB3sdFbGu2lSOzZXChl8UXftmkRb08qHIGryBZU3uvgTLx2kIv/ppDSe8OOwD1GjiyQKrgwjgzyJba9e4yr4B9nHNbPJc5D+WW"
      # admin password will be : dALCDmtpsqrPpKTg48M
    volumes:
      - seq_data:/data
    networks:
      my_network:
        ipv4_address: 172.18.0.7
    ports:
      - "5342:5341"
      - "5343:80"

  local-rabbit-mq:
    image: rabbitmq:4.0.3-management-alpine
    container_name: local-rabbit-mq
    environment:
      RABBITMQ_DEFAULT_USER: "ruser"
      RABBITMQ_DEFAULT_PASS: "eN3NkJq98hYXRtY7p5jLabMpxQPa5M"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/
      - rabbitmq_logs:/var/log/rabbitmq/
    networks:
      my_network:
        ipv4_address: 172.18.0.8
    ports:
      - "5673:5672" # api port
      - "15673:15672" # web port

  #  local-oracle-db:
  #    image: container-registry.oracle.com/database/free:latest
  #    container_name: local-oracle-db
  #    environment:
  #      ORACLE_PWD: "Q9FjrFepHoPp5SsRzq"
  #    volumes:
  #      - oracle_data:/opt/oracle/oradata
  #    networks:
  #      my_network:
  #        ipv4_address: 172.18.0.6
  #    ports:
  #      - "1521:1521"

  local-maildev:
    image: maildev/maildev
    container_name: local-maildev
    networks:
      my_network:
        ipv4_address: 172.18.0.9
    ports:
      - "1081:1080"
      - "1026:1025"

  local-kafka:
    image: apache/kafka:latest
    container_name: local-kafka
    environment:
      KAFKA_KRAFT_MODE: "true"
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://local-kafka:9092,EXTERNAL://localhost:9095
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@local-kafka:9093
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 1
      CLUSTER_ID: 5L6g3nShT-eMCtK--X86sw
    volumes:
      - kafka_data:/var/lib/kafka/data
    networks:
      my_network:
        ipv4_address: 172.18.0.10
    ports:
      - "9093:9092"
      - "9094:9093"
      - "9095:9094"
  # docker run --name local-kafka-ui -d -p 8080:8080 --network local-services_my_network -e DYNAMIC_CONFIG_ENABLED=true -e KAFKA_CLUSTERS_0_NAME=local -e KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=local-kafka:9092 provectuslabs/kafka-ui:latest

  local-elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:9.2.1
    container_name: local-elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=true
      - xpack.security.http.ssl.enabled=false
      - ELASTIC_PASSWORD=tn6ajSkJqfCbeEz89493
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    volumes:
      - es_data:/usr/share/elasticsearch/data
    networks:
      my_network:
        ipv4_address: 172.18.0.11
    ports:
      - "9201:9200"
      - "9301:9300"
  # docker exec -it local-elasticsearch elasticsearch-service-tokens create elastic/kibana kibana-system

  local-kibana:
    image: docker.elastic.co/kibana/kibana:9.2.1
    container_name: local-kibana
    environment:
      ELASTICSEARCH_HOSTS: http://local-elasticsearch:9200
      # ELASTICSEARCH_USERNAME: "elastic"
      ELASTICSEARCH_PASSWORD: "tn6ajSkJqfCbeEz89493"
      ELASTICSEARCH_SERVICE_TOKEN: AAEAAWVsYXN0aWMva2liYW5hL2tpYmFuYS1zeXN0ZW06SmtlMGtxa1RSQlc3TERNN1FLZzljQQ
    networks:
      my_network:
        ipv4_address: 172.18.0.12
    ports:
      - "5602:5601"

networks:
  my_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/24

volumes:
  postgres_data:
  mysql_data:
  mssql_data:
  mongo_data:
  seq_data:
  rabbitmq_data:
  rabbitmq_logs:
  kafka_data:
  es_data:
  #  oracle_data:
# docker run -it mcr.microsoft.com/azure-cli:cbl-mariner2.0

