# redis.conf
user local_redis_user on >3neBg3oX8EEVxNYQE2snX ~* &* +@all

# local_redis_user: custom username
# 3neBg3oX8EEVxNYQE2snX: strong password
# ~* &* +@all: full access (adjust for restricted permissions)
